import os
import sys
import yaml
import pandas as pd
import logging

# Ensure the root directory is in the system path for clean imports
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '../../')))

from src.pipeline.ingestion import TelemetryStreamProducer

logging.basicConfig(level=logging.INFO, format='%(asctime)s [%(levelname)s] %(message)s')

def run_live_replay():
    # 1. Load system configurations to align stream frequency
    config_path = "config/config.yaml"
    with open(config_path, "r") as file:
        config = yaml.safe_load(file)
        
    target_hz = config["system"]["target_frequency_hz"]
    
    # Define the target dataset generated by train.py
    data_source_path = "data/raw_samples/monza_ver_cleaned.csv"
    
    if not os.path.exists(data_source_path):
        logging.error(f"Target data source missing at {data_source_path}. Please execute 'python train.py' first to harvest baseline data.")
        return

    logging.info(f"Loading telemetry file for streaming playback: {data_source_path}")
    telemetry_df = pd.read_csv(data_source_path)
    
    # 2. Extract environment variable if running inside Docker infrastructure
    kafka_broker = os.getenv("KAFKA_BOOTSTRAP_SERVERS", "localhost:9092")
    
    # 3. Instantiate the Kafka producer from ingestion.py
    try:
        streamer = TelemetryStreamProducer(bootstrap_servers=kafka_broker, topic="f1-telemetry-bus")
        
        print("\n" + "="*60)
        print(f"🏎️ LIVE TELEMETRY SIMULATOR ACTIVE | FREQUENCY: {target_hz}Hz")
        print("Streaming data to pit wall dashboard... Press Ctrl+C to abort.")
        print("="*60 + "\n")
        
        # Execute the streaming loop
        streamer.stream_dataframe(telemetry_df, dynamic_hertz=target_hz)
        
    except Exception as e:
        logging.critical(f"Failed to execute Kafka telemetry streaming loop: {str(e)}")

if __name__ == "__main__":
    run_live_replay()